fixed #1304
wix/react-native-calendars pull request #1336
Opened 2020-11-29 10:22 UTC by tamago3keran

This PR fixes issue on #1304. 

When we scroll `WeekCalendar` to the end, it calls `onMomentumScrollEnd`.
And `getDatesArray` is also called in the `onMomentumScrollEnd`.

Maybe it have to change newDateArray on scroll to the end.
But it loads same dateArray.
So I changed code to resolve issue.

|Before|After|
|:--:|:--:|
|<img src="https://user-images.githubusercontent.com/24249859/100538840-775bcf00-3275-11eb-9386-bd51792c4bdc.png" width=400px>|<img src="https://user-images.githubusercontent.com/24249859/100538964-44fea180-3276-11eb-9adc-6e9fd3d21c2a.png" width=400px>|

2020-12-02 09:04 UTC, emilisb requested changes
Hi, thanks for your contribution!

This issue happens because you don't wrap `WeekCalendar` with `CalendarProvider.` `WeekCalendar` is not supposed to be used as a standalone component. We will add docs for this component and we will mention this. Please take a look at an example here: https://github.com/wix/react-native-calendars/blob/0f7037bdcaaa2ecce3b2d992c55c2b0b8d33fb51/example/src/screens/expandableCalendar.js#L175-L189

Unfortunately, we cannot take your PR because it causes issues when `WeekCalendar` is wrapped with `CalendarProvider`. We could take a PR that would allow to use this component standalone, but it should not break behaviour when used with provider.

You can check the correct usage in our demo app `Week calendar` section.

2020-12-02 10:38 UTC, DonOzOn commented
@emilisb i try wrap WeekCalendar with CalendarProvider but it not solve the problem .
i still try solution of @tamago3keran, there are bug with scroll fast and select date but it already generate a new week when scroll to end.Thank all for 
your support

2020-12-02 10:42 UTC, emilisb commented
@DonOzOn please look at the example I sent you, it works in the example app.

2020-12-03 13:33 UTC, emilisb commented
@tamago3keran feel free to open a new Pull Request if you decide to implement standalone support for `CalendarHeader`. I'm closing this PR due to the reasons I mentioned above. Thank you though!

2020-12-03 13:33 UTC, closed without merging